### ISSUE TITLE
Crash in 53.1 while searching quests

### ISSUE THREAD

**Issue by HolgerJeromin** [Helium314/SCEE#429] opened 2023-05-23 20:45 UTC
**How to Reproduce**

Install upgrade

Crash email suggested endless.

**Does it happen in normal StreetComplete?**

**Versions affected**

Android 13
moto g73 5G

       

```
de.westnordost.streetcomplete.data.elementfilter.ParseException: At position 346: A key cannot be named like the reserved word 'and', surround it with quotation marks
at de.westnordost.streetcomplete.data.elementfilter.ElementFiltersParserKt.parseKey(ElementFiltersParser.kt:270)
at de.westnordost.streetcomplete.data.elementfilter.ElementFiltersParserKt.parseTag(ElementFiltersParser.kt:220)
at de.westnordost.streetcomplete.data.elementfilter.ElementFiltersParserKt.parseTags(ElementFiltersParser.kt:141)
at de.westnordost.streetcomplete.data.elementfilter.ElementFiltersParserKt.toElementFilterExpression(ElementFiltersParser.kt:43)
at de.westnordost.streetcomplete.quests.destination.AddDestination$roadsFilter$2.invoke(AddDestination.kt:35)
at de.westnordost.streetcomplete.quests.destination.AddDestination$roadsFilter$2.invoke(AddDestination.kt:27)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at de.westnordost.streetcomplete.quests.destination.AddDestination.getRoadsFilter(AddDestination.kt:27)
at de.westnordost.streetcomplete.quests.destination.AddDestination.getApplicableElements(AddDestination.kt:77)
at de.westnordost.streetcomplete.data.osm.osmquests.OsmQuestController$createQuestsForBBox$deferredQuests$1$1.invokeSuspend(OsmQuestController.kt:203)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by Helium314** [comment] 2023-05-24 04:01
Sorry, copy/paste error when slightly re-ordering a quest filter just before releasing...
Fixed in 53.2

**Closed by Helium314** 2023-05-24 04:01 UTC
Labels: bug

**Comment by HolgerJeromin** [comment] 2023-05-24 04:32
Thanks for the quick fix!
Works.
Just curious: would this crash be possible with editing filter in the scee settings, too?
Perhaps we need better reporting of the failed quest

**Comment by Helium314** [comment] 2023-05-24 05:06
> Just curious: would this crash be possible with editing filter in the scee settings, too?

If you edit the filter in settings, the ok button will be disabled if the filter would cause a crash.

However, if you find a way to still save a broken filter, like editing the preferences file using root access, you should get a similar crash.

> Perhaps we need better reporting to name the failed quest

You can actually see from the logs that the crash is caused by the roads filter of the destination quest (the issue was a duplicate `and`)

**Comment by HolgerJeromin** [comment] 2023-05-24 06:06
Ok, if the Button is locked everything is fine.
Than the reporting via callstack only (aka not in the gui) seems like the correct approach.
