### ISSUE TITLE
Sometimes quest order is not followed

### ISSUE THREAD

**Issue by mnalis** [Helium314/SCEE#513] opened 2024-02-17 19:49 UTC
**How to Reproduce**

I've mostly noticed it on crossings, where there are many quest on same elements. Most times they seems to follow the specified order in preset, but  sometimes (about maybe 3% of the cases or so?) some of the quests come out of order (e.g. "crossing island") 

That is especially noticeable/annoying there, as when you get in the automated flow (e.g. usually all 4 pedestrian crossings are the same) you tent to mechanically answer the same (yes, yes, no, yes, asphalt, good, ...) and then your brain catches up after you've already answered wrong question, so you go to undo... 

But I've also experienced it on other quests (bicycle parking for example). 

Would capturing a video demonstrating the issue help noticeably? If so, would adding some debug logs beforehand help? (I've tried few times but obviously only tried the record the video after it has already happened, and then it didn't want to help while I tried to record dozen videos afterward :smiling_face_with_tear: - so it would probably need dedicated session to catch the evidence on video)

**Expected Behavior**
Quests would always follow order specified in their preset.

**Does it happen in normal StreetComplete?**
Can't say yet, as it happens relatively rarely, and I don't really use vanilla SC much anymore.

**Versions affected**
SCEE 56.1 (and few previous versions at least), Android 14

**Comment by Helium314** [comment] 2024-02-17 20:26
The issue has been there for a long time, and I have no clue what is going on.
Though now I have an idea how to check whether the issue is actually in SCEE code (might also be caused by tangram). It just involves a ton of logging.

Logs or screen recordings of the current version will not help, I think.

**Comment by mnalis** [comment] 2024-02-17 23:48
Note that I have `Show next quest immediately` enabled most of the time, if that makes a difference (although I think the issue also happened when I did not have it, but I cannot confirm that).

If you want to put the required massive logging in (perhaps behind `debug logs` preference?), I'd be happy to run with at and report results when it reproduces.

**Comment by Helium314** [comment] 2024-02-19 10:21
I guess I already found the issue, will be fixed in SC.

**Comment by Helium314** [comment] 2024-02-20 06:58
Or maybe not, see the comment. But it's not an SCEE-exclusive issue, so I'll close this already.
Just comment when it still happens in the next version.

**Closed by Helium314** 2024-02-20 06:58 UTC
Labels: bug
