### ISSUE TITLE
Soundex test Osmose error is test class

### ISSUE THREAD

**Issue by matkoniecz** [Helium314/SCEE#504] opened 2023-12-31 10:00 UTC
Item type 5050/1 is not shown in Osmose at https://osmose.openstreetmap.fr/en/map/#zoom=18&lat=50.06123&lon=19.938302&item=xxxx&level=1%2C2%2C3&issue_uuid=adde1c99-b1b0-fe6a-19dc-2d042f51ba6d but is show in SCEE

It is shown as "Osmose quest: Soundex test"

**Proposed Solution**
Stop showing this error class by default

**Comment by matkoniecz** [comment] 2023-12-31 12:47
weird, it is not showing up for me

and either way it is incomprehensible what it is trying to achieve

![screen](https://github.com/Helium314/SCEE/assets/899988/2cddc214-557f-4adf-a627-f7082f85f89f)

**Comment by Helium314** [comment] 2023-12-31 13:36
> weird, it is not showing up for me

It's the red pin with the black square on your screenshot. On the Osmose website, pins are often at the wrong location, no idea when and why.

> it is incomprehensible what it is trying to achieve

That's also true for the "normal" Osmose issue, unless you go to details and check the description (usually such informtion is in the _subtitle_).
The _description_ reads "_A street name "sounds" similar to that of another street but is not spelled the same way._". Since the issue is on a statue and not on a street, there seems to be a problem with the check.

**Comment by Helium314** [comment] 2024-07-28 20:49
I'll close this issue, as this soundex is a valid osmose issue and the confusion is just caused by name, which is coming from osmose and not SCEE.

**Closed by Helium314** 2024-07-28 20:49 UTC

**Comment by matkoniecz** [comment] 2024-07-28 21:09
What about proposed solution with "stop showing this error class by default"?

**Comment by mnalis** [comment] 2024-07-29 04:31
Well, isn't the _whole_ of Osmose quest disabled by default? There are certainly a number of Osmose quests that I too find too problematic; but current solution seems fine to me - Osmose quest disabled by default, and if enabled, show all high-class priorities only. 

Also note that not only is it chooseable in settings, but users are also offered to disable certain warning classes each time when they are shown (via `Other answers` / `Remove issues with same...`) if they'd prefer never to see that specific Osmose warning ever again.

And if some specific Osmose warning produces too many false positives globally, perhaps it should be suggested there that its [class](https://github.com/osm-fr/osmose-backend/blob/master/doc/0-Index.md#classes-of-issues) should be reduced? Or that it's filter should be updated to remove most of false positives? If there are many FP, surely it affects much more  than just SCEE (but instead affects _all_ Osmose users)?

**Comment by matkoniecz** [comment] 2024-07-31 13:07
> Well, isn't the whole of Osmose quest disabled by default?

Yes, but after enabling it I would expect to not get such broken reports - especially one that was reported as broken long time ago and not fixed

still, it is relatively minor issue

**Comment by Helium314** [comment] 2024-08-07 20:34
> What about proposed solution with "stop showing this error class by default"?

Sorry, I had overlooked that.
So far (I think) I only disabled Osmose issues by default if there is a corresponding quest, or if SCEE is not suitable (relation-related issues).
For the soundex issue I'm not sure. The title really is not understandable, but at the same time the issue can easily be solved in SCEE (if it's an actual issue).
